### ISSUE TITLE
Install SQL Server Express 

### ISSUE THREAD

**Issue by bandredd** [QT-DevOps/AzureIssues#1]
after Install SQL Server Express
choco install sql-server-express -y

I have seen this type of error,below i attached a image...
![sql](https://user-images.githubusercontent.com/47323152/56715597-c8c8e180-6755-11e9-8d6f-de4626645330.PNG)

**Comment by ghost** [comment]
please use this 
choco install sqlserverexpress

**Comment by ghost** [comment]
if ur OS  is 64 bit
use this one also
choco install sql-server-express

not work in 32-bit

**Comment by bandredd** [comment]
Hi QT-DevOps/AzureIssues
Okay, tommorow I will show you frd.
Thanks and Regards
Anil.b

**Comment by bhaskardegala** [comment]
Once try to restart your system and again install it with choco command that you have used

**Comment by ghost** [comment]
close issue if resolved

**Comment by bandredd** [comment]
Yes it's resolved now

**Comment by ghost** [comment]
please close issue
