### ISSUE TITLE
In azure architecture question, is my method right ? putting the process i followed in comments

### ISSUE THREAD

**Issue by suryaDevops1** [QT-DevOps/AzureIssues#10]

**Comment by suryaDevops1** [comment]
My Approach :

webtiersubnet-10.0.1.0/24
bussinesstiersubnet: 10.0.2.0/24
dbtiersubnet : 10.0.3.0/24
managementtiersubnet :10.0.4.0/24

under below vnet:
Vnet is 10.0.0.0/16

Have created 4 nsgs:

nsgforweb
nsgforbussiness
nsgfordb
nsgformanagement

under 
nsgforweb, in inbound rules,
rule 1 - 1000- have kept source as ipaddress-10.0.2.0/24(bussinesstiersubnet range)
rule 2- 1001 have kept source as ipaddress-10.0.3.0/24(dbsubnet range)

here for me webtier subnet should access anything from db and bussiness tier subnet.

is my approach right?

**Comment by bhaskardegala** [comment]
Good to have different nsg for different subnet

**Comment by ghost** [comment]
please close issue
