### ISSUE TITLE
terraform apply . 

### ISSUE THREAD

**Issue by thotagopi** [QT-DevOps/AzureIssues#104]
Hi sir when ever I run the terraform command life using this command terraform apply . getting this error
PS C:\Users\DELL> cd D:\terraform\TerraformZone\Oct20\helo.tf
PS D:\terraform\TerraformZone\Oct20\helo.tf> terraform apply .

Error: error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
status code: 403, request id: 712adbeb-87c6-482d-80cf-c0edb4a267c1

please let me know where I am lacking

**Comment by srmanikanta** [comment]
This is resolved at [devops issues](https://github.com/QT-DevOps/DevOpsIssues/issues/970) please close the issue.
