### ISSUE TITLE
iam starting kibana instance but it is not showing actual kibana server it is showing error

### ISSUE THREAD

**Issue by HarshvardhanVummidi** [QT-DevOps/AzureIssues#108]
im getting
![kibana error](https://user-images.githubusercontent.com/52050152/100407302-0c708500-3036-11eb-9080-cc392fde5145.PNG)

actual output have to get 

![kibana out](https://user-images.githubusercontent.com/52050152/100407324-21e5af00-3036-11eb-8303-2ed3e638de12.PNG)

**Comment by shaikkhajaibrahim** [comment]
Kibana works on 5601 port

**Comment by HarshvardhanVummidi** [comment]
![kibana22](https://user-images.githubusercontent.com/52050152/100453672-5898e500-3089-11eb-9547-b7c62d3a23b4.PNG)
sir i used 5601 port but i ploaded wrong image

**Comment by HarshvardhanVummidi** [comment]
![curl](https://user-images.githubusercontent.com/52050152/100465694-c6e7a280-309d-11eb-9f37-d27f8eada4bc.PNG)

again i restarted the elastic service instance but it is showing connection refused
