### ISSUE TITLE
In Powershell Get-AzResourceGroup giving error

### ISSUE THREAD

**Issue by aadityaGitHub** [QT-DevOps/AzureIssues#13]
In Powershell Get-AzResourceGroup giving error

![image](https://user-images.githubusercontent.com/4330524/58848808-7f997500-86a5-11e9-802f-855c9956dfc5.png)

**Comment by ahmed0129** [comment]
Please do "Connect -AzAccount" then try

**Comment by ghost** [comment]
yes please connect-azaccount then do 
before that install az module in PowerShell
please follow this doc
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps?view=azps-2.1.0

**Comment by sandhyadev** [comment]
powershell version should be 5.1
to check use this :
==>$PSVersionTable
Follow this steps:
==>Set-EXecutionPolicy Unrestricted
==>Install-Module -Name Az -AllowClobber
==>Connect-AzAccount
login to azure
==>Get-AzResourceGroup

**Comment by bhaskardegala** [comment]
Please close the issue if it was resolved

**Comment by aadityaGitHub** [comment]
Thanks for the response but still my issue persists
![image](https://user-images.githubusercontent.com/4330524/59029509-191a7f80-887c-11e9-9767-52435609ac71.png)

**Comment by aadityaGitHub** [comment]
Thanks for your support

**Comment by ghost** [comment]
please do manually once 
I think  problem with your subscription check once

**Comment by ghost** [comment]
adithya 
you dint get a subscription id
please create subscription id
