### ISSUE TITLE
How to get FULL control of the system

### ISSUE THREAD

**Issue by ahmed0129** [QT-DevOps/AzureIssues#14]
In my laptop few of the things are access denied though I"m in Administrator role (user). How to change permissions to the USER to FULL CONTROL. snapshot FYR.
![Capture](https://user-images.githubusercontent.com/51311555/59005739-4e9f7880-883c-11e9-9e2b-760cc36976b0.PNG)

**Comment by ghost** [comment]
tell me that few of the things are access denied

**Comment by sandhyadev** [comment]
This link might help you ahmed.
[](https://www.addictivetips.com/windows-tips/windows-7-access-denied-permission-ownership/)

**Comment by sandhyadev** [comment]
This is might help you ahmed.
https://www.addictivetips.com/windows-tips/windows-7-access-denied-permission-ownership/

**Comment by ahmed0129** [comment]
snapshot FYR, access denied when I try to give perms.

![Capture2](https://user-images.githubusercontent.com/51311555/59075618-4c4a2680-88ef-11e9-9d7b-2c1275dbaeb9.PNG)

**Comment by sandhyadev** [comment]
try this :
https://www.youtube.com/watch?v=f1lhIN4rY1M

**Comment by ahmed0129** [comment]
I have done through google. Thank you all.
