### ISSUE TITLE
Azure SQL Databases Created Successfully

### ISSUE THREAD

**Issue by srinivle** [QT-DevOps/AzureIssues#15]
Create a Azure SQL Database using azure CLI
Try with powershell if possible

Ans. Completed. Worked with both CLI and Powershell. Everything went fine and able 

> az group create --location centralus --name sqldbrg
{
  "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg",
  "location": "centralus",
  "managedBy": null,
  "name": "sqldbrg",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": null
}

> az sql server create --admin-password Srinivas1985 --admin-user mysqldb --location centralus --resource-group sqldbrg --name SrinivasSQLServer
{
  "administratorLogin": "mysqldb",
  "administratorLoginPassword": null,
  "fullyQualifiedDomainName": "srinivassqlserver.database.windows.net",
  "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/srinivassqlserver",
  "identity": null,
  "kind": "v12.0",
  "location": "centralus",
  "name": "srinivassqlserver",
  "resourceGroup": "sqldbrg",
  "state": "Ready",
  "tags": null,
  "type": "Microsoft.Sql/servers",
  "version": "12.0"
}

> az sql db create --name mysqldb --resource-group sqldbrg --server SrinivasSQLServer --edition Basic --service-objective Basic
{
  "catalogCollation": "SQL_Latin1_General_CP1_CI_AS",
  "collation": "SQL_Latin1_General_CP1_CI_AS",
  "createMode": null,
  "creationDate": "2019-06-07T13:44:37.130000+00:00",
  "currentServiceObjectiveName": "Basic",
  "currentSku": {
    "capacity": 5,
    "family": null,
    "name": "Basic",
    "size": null,
    "tier": "Basic"
  },
  "databaseId": "22966617-fb2e-40ba-b0b2-7068568f6dcf",
  "defaultSecondaryLocation": "eastus2",
  "earliestRestoreDate": "2019-06-07T14:14:37.130000+00:00",
  "edition": "Basic",
  "elasticPoolId": null,
  "elasticPoolName": null,
  "failoverGroupId": null,
  "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/srinivassqlserver/databases/mysqldb",
  "kind": "v12.0,user",
  "licenseType": null,
  "location": "centralus",
  "longTermRetentionBackupResourceId": null,
  "managedBy": null,
  "maxLogSizeBytes": null,
  "maxSizeBytes": 2147483648,
  "name": "mysqldb",
  "readScale": "Disabled",
  "recoverableDatabaseId": null,
  "recoveryServicesRecoveryPointId": null,
  "requestedServiceObjectiveName": "Basic",
  "resourceGroup": "sqldbrg",
  "restorableDroppedDatabaseId": null,
  "restorePointInTime": null,
  "sampleName": null,
  "sku": {
    "capacity": 5,
    "family": null,
    "name": "Basic",
    "size": null,
    "tier": "Basic"
  },
  "sourceDatabaseDeletionDate": null,
  "sourceDatabaseId": null,
  "status": "Online",
  "tags": null,
  "type": "Microsoft.Sql/servers/databases",
  "zoneRedundant": false
}

> New-AzSqlServer -ServerName QualityThoughtSQLServer -SqlAdministratorCredentials (Get-Credential) -Location CentralUS -ResourceGroupName sqldbrg

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential

ResourceGroupName        : sqldbrg
ServerName               : qualitythoughtsqlserver
Location                 : centralus
SqlAdministratorLogin    : mysqldb
SqlAdministratorPassword :
ServerVersion            : 12.0
Tags                     :
Identity                 :
FullyQualifiedDomainName : qualitythoughtsqlserver.database.windows.net
ResourceId               : /subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers
                           /qualitythoughtsqlserver

> New-AzSqlDatabase -DatabaseName QualityThoughtSQLDB -Edition Basic -ServerName qualitythoughtsqlserver -ResourceGroupName sqldbrg -RequestedServiceObjectiveName Basic

ResourceGroupName             : sqldbrg
ServerName                    : qualitythoughtsqlserver
DatabaseName                  : QualityThoughtSQLDB
Location                      : centralus
DatabaseId                    : 608be90c-7058-4412-bf3b-295badcd1599
Edition                       : Basic
CollationName                 : SQL_Latin1_General_CP1_CI_AS
CatalogCollation              :
MaxSizeBytes                  : 2147483648
Status                        : Online
CreationDate                  : 6/7/2019 2:38:05 PM
CurrentServiceObjectiveId     : 00000000-0000-0000-0000-000000000000
CurrentServiceObjectiveName   : Basic
RequestedServiceObjectiveName : Basic
RequestedServiceObjectiveId   :
ElasticPoolName               :
EarliestRestoreDate           : 6/7/2019 3:08:05 PM
Tags                          :
ResourceId                    : /subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/se
                                rvers/qualitythoughtsqlserver/databases/QualityThoughtSQLDB
CreateMode                    :
ReadScale                     : Disabled
ZoneRedundant                 : False
Capacity                      : 5
Family                        :
SkuName                       : Basic
LicenseType                   :
AutoPauseDelayInMinutes       :
MinimumCapacity               :

> az sql server list
[
  {
    "administratorLogin": "mysqldb",
    "administratorLoginPassword": null,
    "fullyQualifiedDomainName": "qualitythoughtsqlserver.database.windows.net",
    "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/qualitythoughtsqlserver",
    "identity": null,
    "kind": "v12.0",
    "location": "centralus",
    "name": "qualitythoughtsqlserver",
    "resourceGroup": "sqldbrg",
    "state": "Ready",
    "tags": null,
    "type": "Microsoft.Sql/servers",
    "version": "12.0"
  },
  {
    "administratorLogin": "mysqldb",
    "administratorLoginPassword": null,
    "fullyQualifiedDomainName": "srinivassqlserver.database.windows.net",
    "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/srinivassqlserver",
    "identity": null,
    "kind": "v12.0",
    "location": "centralus",
    "name": "srinivassqlserver",
    "resourceGroup": "sqldbrg",
    "state": "Ready",
    "tags": null,
    "type": "Microsoft.Sql/servers",
    "version": "12.0"
  }
]

> az sql db list -s srinivassqlserver
[
  {
    "catalogCollation": "SQL_Latin1_General_CP1_CI_AS",
    "collation": "SQL_Latin1_General_CP1_CI_AS",
    "createMode": null,
    "creationDate": "2019-06-07T13:42:14.120000+00:00",
    "currentServiceObjectiveName": "Basic",
    "currentSku": {
      "capacity": 5,
      "family": null,
      "name": "Basic",
      "size": null,
      "tier": "Basic"
    },
    "databaseId": "5907de8a-3a5c-4a6c-ac93-f9f57293bcd4",
    "defaultSecondaryLocation": "eastus2",
    "earliestRestoreDate": null,
    "edition": "Basic",
    "elasticPoolId": null,
    "elasticPoolName": null,
    "failoverGroupId": null,
    "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/srinivassqlserver/databases/master",
    "kind": "v12.0,system",
    "licenseType": null,
    "location": "centralus",
    "longTermRetentionBackupResourceId": null,
    "managedBy": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/srinivassqlserver",
    "maxLogSizeBytes": null,
    "maxSizeBytes": 2147483648,
    "name": "master",
    "readScale": "Disabled",
    "recoverableDatabaseId": null,
    "recoveryServicesRecoveryPointId": null,
    "requestedServiceObjectiveName": "Basic",
    "resourceGroup": "sqldbrg",
    "restorableDroppedDatabaseId": null,
    "restorePointInTime": null,
    "sampleName": null,
    "sku": {
      "capacity": 5,
      "family": null,
      "name": "Basic",
      "size": null,
      "tier": "Basic"
    },
    "sourceDatabaseDeletionDate": null,
    "sourceDatabaseId": null,
    "status": "Online",
    "tags": null,
    "type": "Microsoft.Sql/servers/databases",
    "zoneRedundant": false
  },
  {
    "catalogCollation": "SQL_Latin1_General_CP1_CI_AS",
    "collation": "SQL_Latin1_General_CP1_CI_AS",
    "createMode": null,
    "creationDate": "2019-06-07T13:44:37.130000+00:00",
    "currentServiceObjectiveName": "Basic",
    "currentSku": {
      "capacity": 5,
      "family": null,
      "name": "Basic",
      "size": null,
      "tier": "Basic"
    },
    "databaseId": "22966617-fb2e-40ba-b0b2-7068568f6dcf",
    "defaultSecondaryLocation": "eastus2",
    "earliestRestoreDate": "2019-06-07T13:53:15.547000+00:00",
    "edition": "Basic",
    "elasticPoolId": null,
    "elasticPoolName": null,
    "failoverGroupId": null,
    "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/srinivassqlserver/databases/mysqldb",
    "kind": "v12.0,user",
    "licenseType": null,
    "location": "centralus",
    "longTermRetentionBackupResourceId": null,
    "managedBy": null,
    "maxLogSizeBytes": null,
    "maxSizeBytes": 2147483648,
    "name": "mysqldb",
    "readScale": "Disabled",
    "recoverableDatabaseId": null,
    "recoveryServicesRecoveryPointId": null,
    "requestedServiceObjectiveName": "Basic",
    "resourceGroup": "sqldbrg",
    "restorableDroppedDatabaseId": null,
    "restorePointInTime": null,
    "sampleName": null,
    "sku": {
      "capacity": 5,
      "family": null,
      "name": "Basic",
      "size": null,
      "tier": "Basic"
    },
    "sourceDatabaseDeletionDate": null,
    "sourceDatabaseId": null,
    "status": "Online",
    "tags": null,
    "type": "Microsoft.Sql/servers/databases",
    "zoneRedundant": false
  }
]

> az sql db list -s qualitythoughtsqlserver
[
  {
    "catalogCollation": "SQL_Latin1_General_CP1_CI_AS",
    "collation": "SQL_Latin1_General_CP1_CI_AS",
    "createMode": null,
    "creationDate": "2019-06-07T13:54:20.493000+00:00",
    "currentServiceObjectiveName": "System2",
    "currentSku": {
      "capacity": 0,
      "family": null,
      "name": "System",
      "size": null,
      "tier": "System"
    },
    "databaseId": "a1da20a2-80be-4fd5-b94a-d9743cc8bc1f",
    "defaultSecondaryLocation": "eastus2",
    "earliestRestoreDate": null,
    "edition": "System",
    "elasticPoolId": null,
    "elasticPoolName": null,
    "failoverGroupId": null,
    "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/qualitythoughtsqlserver/databases/master",
    "kind": "v12.0,system",
    "licenseType": null,
    "location": "centralus",
    "longTermRetentionBackupResourceId": null,
    "managedBy": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/qualitythoughtsqlserver",
    "maxLogSizeBytes": null,
    "maxSizeBytes": 32212254720,
    "name": "master",
    "readScale": "Disabled",
    "recoverableDatabaseId": null,
    "recoveryServicesRecoveryPointId": null,
    "requestedServiceObjectiveName": "System2",
    "resourceGroup": "sqldbrg",
    "restorableDroppedDatabaseId": null,
    "restorePointInTime": null,
    "sampleName": null,
    "sku": {
      "capacity": 0,
      "family": null,
      "name": "System",
      "size": null,
      "tier": "System"
    },
    "sourceDatabaseDeletionDate": null,
    "sourceDatabaseId": null,
    "status": "Online",
    "tags": null,
    "type": "Microsoft.Sql/servers/databases",
    "zoneRedundant": false
  },
  {
    "catalogCollation": "SQL_Latin1_General_CP1_CI_AS",
    "collation": "SQL_Latin1_General_CP1_CI_AS",
    "createMode": null,
    "creationDate": "2019-06-07T14:38:05.693000+00:00",
    "currentServiceObjectiveName": "Basic",
    "currentSku": {
      "capacity": 5,
      "family": null,
      "name": "Basic",
      "size": null,
      "tier": "Basic"
    },
    "databaseId": "608be90c-7058-4412-bf3b-295badcd1599",
    "defaultSecondaryLocation": "eastus2",
    "earliestRestoreDate": "2019-06-07T15:08:05.693000+00:00",
    "edition": "Basic",
    "elasticPoolId": null,
    "elasticPoolName": null,
    "failoverGroupId": null,
    "id": "/subscriptions/2c282192-6173-41b7-b92e-facdabe8012d/resourceGroups/sqldbrg/providers/Microsoft.Sql/servers/qualitythoughtsqlserver/databases/QualityThoughtSQLDB",
    "kind": "v12.0,user",
    "licenseType": null,
    "location": "centralus",
    "longTermRetentionBackupResourceId": null,
    "managedBy": null,
    "maxLogSizeBytes": null,
    "maxSizeBytes": 2147483648,
    "name": "QualityThoughtSQLDB",
    "readScale": "Disabled",
    "recoverableDatabaseId": null,
    "recoveryServicesRecoveryPointId": null,
    "requestedServiceObjectiveName": "Basic",
    "resourceGroup": "sqldbrg",
    "restorableDroppedDatabaseId": null,
    "restorePointInTime": null,
    "sampleName": null,
    "sku": {
      "capacity": 5,
      "family": null,
      "name": "Basic",
      "size": null,
      "tier": "Basic"
    },
    "sourceDatabaseDeletionDate": null,
    "sourceDatabaseId": null,
    "status": "Online",
    "tags": null,
    "type": "Microsoft.Sql/servers/databases",
    "zoneRedundant": false
  }
]

**Comment by ghost** [comment]
good srinivas
and close issue
this is for raise issue if you get any error
