### ISSUE TITLE
Regarding CIS

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/AzureIssues#16]
Hi

What is CIS in Azure.
CIS benchmark fof Azure / Azure virtual machines / Azure subscriptions

Please give any idea regarding that.

**Comment by sandhyadev** [comment]
CIS(center for internet security) :
https://azure.microsoft.com/mediahandler/files/resourcefiles/cis-microsoft-azure-foundations-security-benchmark/CIS_Microsoft_Azure_Foundations_Benchmark_v1.0.0.pdf
