### ISSUE TITLE
IDs for terraform

### ISSUE THREAD

**Issue by khatrigopal** [QT-DevOps/AzureIssues#17]
Hi
How can i found
subscription_id
client_id
client_secret
tenant_id

for azure account so i can use in terraform

**Comment by sandhyadev** [comment]
Execute the foolowing steps to get the id's
 az login
 az ad sp create-for-rbac --query "{ client_id: appId, client_secret: password, tenant_id: tenant }"
 az account show --query "{ subscription_id: id }"

**Comment by satyamuralidhar** [comment]
https://github.com/immurali5/Azure-Terraform.git

**Comment by NareshAbbanapuri** [comment]
close issue
