### ISSUE TITLE
error while downloading vitualbox from chocolatey

### ISSUE THREAD

**Issue by lakshmivennapusa** [QT-DevOps/AzureIssues#18]
![Screenshot (3)](https://user-images.githubusercontent.com/51362024/61208359-dc606480-a714-11e9-8888-d8200e9c69b2.png)

**Comment by RamBoddapati** [comment]
@lakshmivennapusa , 
it looks you have installed virtual box manually  and tried to do  it again form  choco. Please provide choco logs, we can  traceout this issue.

**Comment by ramjagadeeshkumar** [comment]
First uninstall you virtual box with chocolate 
Go to path of chocolatey and delete you virtual box file from it 

And try now install your virtual box with choco command 

If it's not working then go to install virtual box older version because in some system it's not working update version

**Comment by neelaraokala** [comment]
First uninstall virtual box , then try to force install by using the command
Choco install -f virtualbox -y .
This command will work.

**Comment by NareshAbbanapuri** [comment]
close issue
