### ISSUE TITLE
RDP not accessible when I click from Azure Portal

### ISSUE THREAD

**Issue by ahmed0129** [QT-DevOps/AzureIssues#19]
![image](https://user-images.githubusercontent.com/51311555/61582384-cf45da00-ab47-11e9-9248-0f3bd47603a3.png)

![image](https://user-images.githubusercontent.com/51311555/61582387-e84e8b00-ab47-11e9-800d-c65240978403.png)

**Comment by ghost** [comment]
enable port 3389

**Comment by ahmed0129** [comment]
> enable port 3389

Hi Naresh,

I have enabled/created new rule in firewall, if I'm missing something, can you elaborate how to enable

**Comment by ghost** [comment]
in networking section has two options  inbound and outbound rules
allow 3389 RDP rule in indound

**Comment by ahmed0129** [comment]
> in networking section has two options inbound and outbound rules
> allow 3389 RDP rule in indound

Naresh, Please let me know the path/navigation

**Comment by sandhyadev** [comment]
follow this link
https://docs.microsoft.com/en-us/azure/virtual-machines/troubleshooting/troubleshoot-rdp-nsg-problem
