### ISSUE TITLE
JSON script written today in class

### ISSUE THREAD

**Issue by ahmed0129** [QT-DevOps/AzureIssues#20]
Can someone please share the script of todays (07/26) class or let me know where I can find in any path? or please call me 7997079789

**Comment by ramjagadeeshkumar** [comment]
https://github.com/asquarezone

Sir will be share on this repository 

If sir is not share that work you have do it and then you getting any issue  share it here 

Will help you where you struck

**Comment by NareshAbbanapuri** [comment]
please close issue
