### ISSUE TITLE
Error while creating custom role

### ISSUE THREAD

**Issue by nikhil-ops** [QT-DevOps/AzureIssues#21]
Below Error is occurring while executing New-AZRoleDefinition  -InputFile

New-AzRoleDefinition : Scope '/ ' should have even number of parts

Note: Unable to upload json file due format support, so attached text file.

![Error](https://user-images.githubusercontent.com/54447555/64060599-a441b200-cbec-11e9-9a1a-c97afc5a79fb.PNG)
[Reader.txt](https://github.com/QT-DevOps/AzureIssues/files/3562167/Reader.txt)

**Comment by anon-42** [comment]
Mahn, 
There is a syntax problem in your Script.
In your assignable scops, instead of ..."/1e568163-de36-4e79-a988-636f298a8fc4"...
Add this ... "/subscriptions/1e568163-de36-4e79-a988-636f298a8fc4"....
