### ISSUE TITLE
unable to create virtual network

### ISSUE THREAD

**Issue by khajasaheb** [QT-DevOps/AzureIssues#23]
Hello Sir,

while creating virtual network in portal it was getting error as "resource was disallowed by policy".

Kindly provide me a solution.

Thanks,
khan

**Comment by shaikkhajaibrahim** [comment]
Can you describe more about the machine type your account (free trail) or pay as you go etc & screen shot of error
________________________________

**Comment by khajasaheb** [comment]
Hello Sir,

Machine type > Windows 10
Account Type > Free Trail

Attached error containing image fyr.

Thanks,
khan

**Comment by khajasaheb** [comment]
![azure vnet error](https://user-images.githubusercontent.com/55074870/64520477-e3ba7d80-d313-11e9-88a6-61b5f925fe0f.PNG)

**Comment by khajasaheb** [comment]
Hello Sir,

Waiting for your response .

Thanks,
Khan

**Comment by khajasaheb** [comment]
Hello Sir,

I was unable to do any activity in my account .

Windows type : 10
subscription    : free

today i tried to create a vm but is is getting error as the same as i mentioned above.

Kindly provide me solution sir.

![image](https://user-images.githubusercontent.com/55074870/64712014-2d53c580-d4d8-11e9-8eaf-891cd434f67d.png)

Thanks,
Khan

**Comment by khajasaheb** [comment]
{
  "code": "InvalidTemplateDeployment",
  "message": "The template deployment failed with multiple errors. Please see details for more information.",
  "details": [
    {
      "code": "RequestDisallowedByPolicy",
      "target": "monitoringvm251",
      "message": "Resource 'monitoringvm251' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Require tag and its value\",\"id\":\"/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea\"},\"policyDefinition\":{\"name\":\"Require tag and its value\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62\"}}]'.",
      "additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "Require tag and its value",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "False",
                  "expression": "tags[environment]",
                  "path": "tags[environment]",
                  "targetValue": "test",
                  "operator": "Equals"
                }
              ]
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionName": "1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionEffect": "deny",
            "policyAssignmentId": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentName": "4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentDisplayName": "Require tag and its value",
            "policyAssignmentScope": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef",
            "policyAssignmentParameters": {
              "tagName": {
                "value": "environment"
              },
              "tagValue": {
                "value": "test"
              }
            }
          }
        }
      ]
    },
    {
      "code": "RequestDisallowedByPolicy",
      "target": "monitoringvm-nsg",
      "message": "Resource 'monitoringvm-nsg' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Require tag and its value\",\"id\":\"/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea\"},\"policyDefinition\":{\"name\":\"Require tag and its value\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62\"}}]'.",
      "additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "Require tag and its value",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "False",
                  "expression": "tags[environment]",
                  "path": "tags[environment]",
                  "targetValue": "test",
                  "operator": "Equals"
                }
              ]
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionName": "1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionEffect": "deny",
            "policyAssignmentId": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentName": "4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentDisplayName": "Require tag and its value",
            "policyAssignmentScope": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef",
            "policyAssignmentParameters": {
              "tagName": {
                "value": "environment"
              },
              "tagValue": {
                "value": "test"
              }
            }
          }
        }
      ]
    },
    {
      "code": "RequestDisallowedByPolicy",
      "target": "monitoring-vnet",
      "message": "Resource 'monitoring-vnet' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Require tag and its value\",\"id\":\"/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea\"},\"policyDefinition\":{\"name\":\"Require tag and its value\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62\"}}]'.",
      "additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "Require tag and its value",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "False",
                  "expression": "tags[environment]",
                  "path": "tags[environment]",
                  "targetValue": "test",
                  "operator": "Equals"
                }
              ]
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionName": "1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionEffect": "deny",
            "policyAssignmentId": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentName": "4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentDisplayName": "Require tag and its value",
            "policyAssignmentScope": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef",
            "policyAssignmentParameters": {
              "tagName": {
                "value": "environment"
              },
              "tagValue": {
                "value": "test"
              }
            }
          }
        }
      ]
    },
    {
      "code": "RequestDisallowedByPolicy",
      "target": "monitoringvm-ip",
      "message": "Resource 'monitoringvm-ip' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Require tag and its value\",\"id\":\"/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea\"},\"policyDefinition\":{\"name\":\"Require tag and its value\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62\"}}]'.",
      "additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "Require tag and its value",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "False",
                  "expression": "tags[environment]",
                  "path": "tags[environment]",
                  "targetValue": "test",
                  "operator": "Equals"
                }
              ]
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionName": "1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionEffect": "deny",
            "policyAssignmentId": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentName": "4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentDisplayName": "Require tag and its value",
            "policyAssignmentScope": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef",
            "policyAssignmentParameters": {
              "tagName": {
                "value": "environment"
              },
              "tagValue": {
                "value": "test"
              }
            }
          }
        }
      ]
    },
    {
      "code": "RequestDisallowedByPolicy",
      "target": "monitoringvm",
      "message": "Resource 'monitoringvm' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Require tag and its value\",\"id\":\"/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea\"},\"policyDefinition\":{\"name\":\"Require tag and its value\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62\"}}]'.",
      "additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "Require tag and its value",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "False",
                  "expression": "tags[environment]",
                  "path": "tags[environment]",
                  "targetValue": "test",
                  "operator": "Equals"
                }
              ]
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionName": "1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionEffect": "deny",
            "policyAssignmentId": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentName": "4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentDisplayName": "Require tag and its value",
            "policyAssignmentScope": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef",
            "policyAssignmentParameters": {
              "tagName": {
                "value": "environment"
              },
              "tagValue": {
                "value": "test"
              }
            }
          }
        }
      ]
    },
    {
      "code": "RequestDisallowedByPolicy",
      "target": "monitoringdiag767",
      "message": "Resource 'monitoringdiag767' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"Require tag and its value\",\"id\":\"/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea\"},\"policyDefinition\":{\"name\":\"Require tag and its value\",\"id\":\"/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62\"}}]'.",
      "additionalInfo": [
        {
          "type": "PolicyViolation",
          "info": {
            "policyDefinitionDisplayName": "Require tag and its value",
            "evaluationDetails": {
              "evaluatedExpressions": [
                {
                  "result": "False",
                  "expression": "tags[environment]",
                  "path": "tags[environment]",
                  "targetValue": "test",
                  "operator": "Equals"
                }
              ]
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionName": "1e30110a-5ceb-460c-a204-c1c3969c6d62",
            "policyDefinitionEffect": "deny",
            "policyAssignmentId": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef/providers/Microsoft.Authorization/policyAssignments/4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentName": "4e8d0ca2665e4f5fa05c6fea",
            "policyAssignmentDisplayName": "Require tag and its value",
            "policyAssignmentScope": "/subscriptions/9eade0ee-6908-49d0-a480-dbc5c833e0ef",
            "policyAssignmentParameters": {
              "tagName": {
                "value": "environment"
              },
              "tagValue": {
                "value": "test"
              }
            }
          }
        }
      ]
    }
  ]
}

**Comment by khajasaheb** [comment]
Kindly check and provide me a solution sir.

Thanks

**Comment by khajasaheb** [comment]
Hello Sir,

I have studied blogs and gone through youtube vedios and issue got resolved.

Thanks,
khan
