### ISSUE TITLE
not creating virtual machine for both portal and CLI

### ISSUE THREAD

**Issue by swarami** [QT-DevOps/AzureIssues#24]
Hello Sir,

Am not able to create virtual machine from both Portal and CLI, kindly give me a solution.
![image](https://user-images.githubusercontent.com/46607257/64762086-7e30e180-d50b-11e9-9bca-8dea4a7d8658.png)
![image](https://user-images.githubusercontent.com/46607257/64762311-ed0e3a80-d50b-11e9-8066-483b23b4e649.png)
am getting 400 error.

Regards,
Nagesh

**Comment by shaikkhajaibrahim** [comment]
Hi Nagesh,

First thing please raise the issue on Azure Portal to microsoft to findout the reason.
Schedule your time with naresh to find to know more.
Thanks,
Khaja
________________________________
