### ISSUE TITLE
Unable to open VM using RDP

### ISSUE THREAD

**Issue by antony2** [QT-DevOps/AzureIssues#25]
Hi
Am unable to open VM using RDP am getting the following error
![Error](https://user-images.githubusercontent.com/15454439/64859907-2bf5da80-d649-11e9-9aad-a05779ff3293.JPG)

**Comment by neelaraokala** [comment]
Hi antony2,
it is a authentication error, so once again go to connect , and download the RDP file and do mstsc -v Publicipaddress
then after enter you instance configured username and password correctly.
if it  is showing your configured password(represented ip address) is wrong . reset password as
**go to Reset password under Support + troubleshooting blade and add existed username of your VM and new password then update it.**
now comes to VM connect then do RDP connect as mentioned above(downloading RDP file and mstsc -v ipaddress)

**Comment by NareshAbbanapuri** [comment]
hi 
enable port 3389 
download RDP file or run command mstsc -v ipaddress
requires username and password
