### ISSUE TITLE
unable to create vm instances by using stress command

### ISSUE THREAD

**Issue by sandeep5683** [QT-DevOps/AzureIssues#26]
i am unable to create vm instances by using stress command 
 stress --cpu 8 --io 4 --vm 2 --vm-bytes 128M --timeout 10m

**Comment by shaikkhajaibrahim** [comment]
Stress command will not create vm instance. It will stress or create load on your cpu/memory/disk
________________________________

**Comment by sandeep5683** [comment]
![vmss](https://user-images.githubusercontent.com/48408567/65052250-df333c00-d987-11e9-9184-2931cf549df8.PNG)

**Comment by sandeep5683** [comment]
In the above scenario i am trying to stress on cpu to create instances automatically, but i am unable to do that. please let me know how to do that.

**Comment by NareshAbbanapuri** [comment]
Hi sandeep
please follow this documents
[clickhere](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/quick-create-portal)
