### ISSUE TITLE
Free trail was ended

### ISSUE THREAD

**Issue by khajasaheb** [QT-DevOps/AzureIssues#27]
Hello Sir,

My free trail account was ended .

Is there any secondary way to make practice? Please let me know.

Thanks,
Khan

**Comment by nikhil-ops** [comment]
There is no other way for same subscription. You can create new azure account...that works

**Comment by khajasaheb** [comment]
okay will the other account works with the same credit card which i have given it for the older one.

Or do i need another card?

**Comment by krishna1952** [comment]
same credit card cannot be used for two accounts

**Comment by khajasaheb** [comment]
Thanks you..!
