### ISSUE TITLE
Unable to proceed further to install in Virtual Box

### ISSUE THREAD

**Issue by ahmed0129** [QT-DevOps/AzureIssues#28]
Hi

I'm installing centOS in Virtual Box, when I click on virtual machine and given the ISO path, I'm not able to move further, no mouse or keyboard are accessible in the window. Here is the attaching recorded steps. Please suggest ASAP.

Click below:

[vb error.zip](https://github.com/QT-DevOps/AzureIssues/files/3650807/vb.error.zip)

**Comment by shaikkhajaibrahim** [comment]
This is not a forum for vbox
