### ISSUE TITLE
automation drive

### ISSUE THREAD

**Issue by krishna1952** [QT-DevOps/AzureIssues#29]
to create automation drive using github, jenkins ci/cd pipeline, azure, nexus, ansible , terraform &maven.

i have created  a ci/cd jekins pipeline, but how to integrate it with terraform, ansible and nexus.
![image](https://user-images.githubusercontent.com/54786477/65708765-f3c0b400-e0ac-11e9-9769-4f247246326f.png)

**Comment by shaikkhajaibrahim** [comment]
From  Jenkins pipeline script call terraform command using groovy or if it is free style use invoke shell and call terraform cmd line
