### ISSUE TITLE
Getting error while trying vagrant UP

### ISSUE THREAD

**Issue by saikiranbende** [QT-DevOps/AzureIssues#3]
Could you please check and help me in making vagrant up as m getting below error:
![Vagrant error](https://user-images.githubusercontent.com/39144011/56791718-66d7ad00-6825-11e9-8826-c550cdf7d94d.PNG)

**Comment by sandhyadev** [comment]
Are you working in windows 10 ?

**Comment by saikiranbende** [comment]
Yes Wndows 10 Pro

**Comment by anon-42** [comment]
Go to windows features disable Hyper-V , and restart machine, then try agian, If you want to try with virtualbox 
Or 
 if you want to run  in Hyper-V comment the line _config.vm.provider "virtualbox" do |vb|_ , _vb.gui = true_ and _end_ next to that.  
Also try to use command like "vagrant up --provider hyperv"

**Comment by ghost** [comment]
use only one provider ( hyperv or virtualbox)
