### ISSUE TITLE
not able to connect linux virtual machine in azure

### ISSUE THREAD

**Issue by swarami** [QT-DevOps/AzureIssues#30]
Hi Sir,

am not able to connect to linux virtual machine ip address:@40.122.79.89 with username and password.Getting permission denied and kindly help me.
![image](https://user-images.githubusercontent.com/46607257/66012934-36acce00-e497-11e9-85cd-311d057b99b7.png)

Regards,
Nagesh.

**Comment by ghost** [comment]
please enter right password

**Comment by gatkaraju** [comment]
give sudo command   or  enter right password
