### ISSUE TITLE
unable to give alert rule..attaching screen shot

### ISSUE THREAD

**Issue by abhiram2708** [QT-DevOps/AzureIssues#31]
unable to give alert rule..attaching screen shot
![error_azure](https://user-images.githubusercontent.com/34208039/66042288-ab384900-e539-11e9-86a9-42fa3b0c90de.png)

**Comment by ghost** [comment]
there is no subscription

**Comment by srinivas-reddy-mula** [comment]
Just register your Subscription to Microsoft.Insights
 Execute the command
   Register-AzResourceProvider -ProviderNamespace Microsoft.Insights
follow(https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-register-provider-errors)
