### ISSUE TITLE
Issue while creating AKS cluster form CLI and Console

### ISSUE THREAD

**Issue by kishoregudidha** [QT-DevOps/AzureIssues#32]
Hi,
Please help me on below issue.
I am trying to create AKS cluster form command line and console , but unfortunately i could not fix the issue .  I am getting below error when i executed .

CMD what i passed :

 az aks create \
>     --resource-group myResourceGroup \
>     --name TESTAKSCluster \
>     --node-count 2 \
>     --generate-ssh-keys \
>     --attach-acr kishore123

ERROR: 

Deployment failed. Correlation ID: 68a6e3ef-d15a-485e-ba29-899f79de3e37. Reconcile standard load balancer failed. Details: standardLoadBalancerReconciler retry failed: Code="MissingSubscriptionRegistration" Message="The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions." Details=[{"code":"MissingSubscriptionRegistration","message":"The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions.","target":"Microsoft.Network"}].
 
Thanks,
Kishore.g

**Comment by Abbanapuri** [comment]
please upgrade subscription to pay as you go
or else create new account
