### ISSUE TITLE
Error occured while preparing hyper-v for assessment

### ISSUE THREAD

**Issue by manikanta-419** [QT-DevOps/AzureIssues#33]
After successfully run the Microsoft documentation on powershell, I can executed the 'CertUtil -Hashfile..
Error occured while excute the next command on the documentation 
which is 
PS C:\Users\manikanta\Downloads> MicrosoftAzureMigrate-Hyper-V.ps1
![20191028_143256](https://user-images.githubusercontent.com/57040317/67667099-205d3980-f993-11e9-9af9-947a85cd2071.jpg)

**Comment by lakshmivennapusa** [comment]
Give only two arguments after “certutil -hashfile path\microsoft sha256 . After executing this just give microsoft file.

**Comment by manikanta-419** [comment]
Its workout thanqq for ur valuable time

**Comment by ABBANAPURI0445** [comment]
please close issue
