### ISSUE TITLE
Azure Free trial ended and disabled

### ISSUE THREAD

**Issue by rajeshpothuri** [QT-DevOps/AzureIssues#34]
Hi Team,

I couldn't find pay-as-you-go subscription to upgrade as my free trial subscription ended.

Attached the screenshot for reference. Can someone assist me on this.
![Azure subscription disabled](https://user-images.githubusercontent.com/58278802/69773003-9386e500-11b7-11ea-9574-7872de62d05c.JPG)

**Comment by ABBANAPURI0445** [comment]
yes select no technical support and go-ahead
