### ISSUE TITLE
Configure appliance: WinRM operation & WinRm firewall error

### ISSUE THREAD

**Issue by inikhil-ops** [QT-DevOps/AzureIssues#35]
I am performing Hyper-V to azure migration, In the **assessment config.appliance** error(attached) is occurring and cannot proceed further with discovery.

Please help me on resolution of fix

performed below activities:
1.added Inbound security rule for WinRm HTTPS-5986
2.created Firewall rule inside host VM
3.enabled 5986 and bind the certificate
![HostVM_Firewall](https://user-images.githubusercontent.com/57178172/69817356-6de1f600-1220-11ea-8df2-249bcc13655a.png)
![inbound_security rule](https://user-images.githubusercontent.com/57178172/69817357-6de1f600-1220-11ea-871a-ed2ead1b2ffc.PNG)
![winrm](https://user-images.githubusercontent.com/57178172/69817358-6de1f600-1220-11ea-8882-3480aa64474a.png)

**Comment by khajasaheb** [comment]
Is this resolved ?

if yes could you please provide me steps.

Thanks
