### ISSUE TITLE
Trying to connect to jenkins serverip

### ISSUE THREAD

**Issue by rshantam** [QT-DevOps/AzureIssues#36]
Created Ubuntu VM from Azure portal
Installed Jenkins on Ubuntu Vm
[ Jenkins Post-Install Configuration 
    Navigate to the url http://<jenkinsserverip>:8080 ]

Trying my link : http://52.165.37.28:8080
Getting below error :

This site can’t be reached52.165.37.28 took too long to respond.
Search Google for 165 8080
ERR_CONNECTION_TIMED_OUT

**Comment by ABBANAPURI0445** [comment]
please check jenkins status
and nsg also
