### ISSUE TITLE
Duplicate project

### ISSUE THREAD

**Issue by sandeep5683** [QT-DevOps/AzureIssues#4]
hi while i m creating new freestyle project in jenkins portal, the project will creating 4 times in the same way. please let me know how to sort it out.

**Comment by shaikkhajaibrahim** [comment]
Please raise this on DevOps issues

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bhaskardegala** [comment]
Sandeep please close this isuue here

**Comment by sandeep5683** [comment]
thanks everyone
