### ISSUE TITLE
GIT : in My local PC ".Git" Folder is not getting created in any of local windows PC

### ISSUE THREAD

**Issue by cprasnsp55** [QT-DevOps/AzureIssues#41]
Hi,
i have tried creating "Git local repository" in laptop which is an windows based machine,
i have Git installed at this location  :C:\Program Files\Git

when i am trying run the below commands :
PS C:\> git --version
git version 2.24.1.windows.2
i can see that GIT is installed in my local pc.
below are commands i have tired but i could  that  .GIT Folder is Not getting created,kindly please guide me:
PS C:\> mkdir newgit

    Directory: C:\

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        1/23/2020   9:02 PM                newgit

PS C:\> cd newgit
PS C:\newgit> git init
Initialized empty Git repository in C:/newgit/.git/
but i am Not   able to view the ".Git" Folder in  any of the  local pc.
let me know if any setting i need to do before creating  a git respository

Thanks
Prashanth

**Comment by HSuryadevara** [comment]
Please check hidden files

**Comment by cprasnsp55** [comment]
Thanks  i am able to see now the .git folders
