### ISSUE TITLE
WinRM client cannot process the request because the server name cannot be resolved.

### ISSUE THREAD

**Issue by vamsi0848** [QT-DevOps/AzureIssues#46]
![Screenshot (23)](https://user-images.githubusercontent.com/57513633/73723518-38d9ae80-474f-11ea-9b77-c9281fc2b968.png)

**Comment by shaikkhajaibrahim** [comment]
I need the full list of steps followed by you,

1. Did you run the powershell script on the server?

Try with private ip address or
configure the DNS Name and use the DNS name of the hyperv host
