### ISSUE TITLE
Unable to Launch jenkins in Chrome browser after sucessfull install on Redhat linux in AWS

### ISSUE THREAD

**Issue by cprasnsp55** [QT-DevOps/AzureIssues#47]
Hi All,
i am Unable to Launch jenkins in Chrome browser after i have successful install on Redhat Linux in AWS.
i have attached the screens shot for jenkins service up and running
and also i have attaching AWS red hat linux inbound rules screen shot for your reference.
please let me know where issue why i am not able to launch jenkins on browser.
i am getting below message in chrome browser :

This site can’t be reached 18.224.181.177 refused to connect.
[](url)

Thanks
Prashanth
![Jenkins_powershell_jenkings server status running](https://user-images.githubusercontent.com/28658467/75001899-8aed2600-5417-11ea-8550-fe72e9fdf09b.png)
[redhatlinuxinstance_security group setting- inbound and outbound.docx](https://github.com/QT-DevOps/AzureIssues/files/4234132/redhatlinuxinstance_security.group.setting-.inbound.and.outbound.docx)

**Comment by ABBANAPURI0445** [comment]
RedHat might need a subscription

**Comment by shaikkhajaibrahim** [comment]
This is not a place for AWS issues
