### ISSUE TITLE
hai, azure version in powershall

### ISSUE THREAD

**Issue by lokesh8433** [QT-DevOps/AzureIssues#48]
issues in azure cli
![Capture](https://user-images.githubusercontent.com/55614674/75235417-344e6600-57e2-11ea-84e2-e68b54526007.PNG)

**Comment by HSuryadevara** [comment]
Did you install cli?
If not install it first and reopen PS as admin

**Comment by lokesh8433** [comment]
yes i do install currectly after check issue rise

**Comment by lokesh8433** [comment]
i do check in poweshall admi but issue

**Comment by shaikkhajaibrahim** [comment]
I think re-launch after installation should be done.

even after that if it is not working i would like to evaluate your installation approach
