### ISSUE TITLE
virtual machine creation

### ISSUE THREAD

**Issue by AzharShabbirKhan** [QT-DevOps/AzureIssues#49]
Hello,
I was getting this error while creating VM 
![Azzure issue1](https://user-images.githubusercontent.com/53536368/75261485-6ca67200-57eb-11ea-9826-7d979248a6f2.png). 
First I create
 RG then creant VNET. 

Please guide me.
Thanks.

**Comment by HSuryadevara** [comment]
Try after creating a new resource group

**Comment by shaikkhajaibrahim** [comment]
Please create resource group first while using as this deployment expects the resource group to be empty
