### ISSUE TITLE
Unable to install virtualbox in my Laptop

### ISSUE THREAD

**Issue by suryaDevops1** [QT-DevOps/AzureIssues#5]
Hi All,

My Windows edition : Windows 10 Home Single Language

While installing virtual box , Iam getting the below error:
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://download.virtualbox.org/virtualbox/6.0.6/VirtualBox-6.0.6-130049-Win.exe'. Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."
The install of virtualbox was NOT successful.

Can Anyone help me

**Comment by Karthick-Gopalakrishnan** [comment]
Hello Suyra,

Site got some issues, Try to download from below portal and install it manually 

https://filehippo.com/download_virtualbox/

**Comment by suryaDevops1** [comment]
> Hello Suyra,
> 
> Site got some issues, Try to download from below portal and install it manually
> 
> https://filehippo.com/download_virtualbox/

Thanks Karthick !! Got that resolved !!

**Comment by ghost** [comment]
if you install via choco
PowerShell run as admin  and try
