### ISSUE TITLE
Azure create VM CLI

### ISSUE THREAD

**Issue by PavanRajuAlluri** [QT-DevOps/AzureIssues#50]
I am having below error eventhough i have tried with several image names. Could you please help me on this.

![image](https://user-images.githubusercontent.com/61484277/75412943-0a00c380-591c-11ea-9488-f0dd490c1fec.png)

**Comment by shaikkhajaibrahim** [comment]
Error clearly speaks about the default user admin is not allowed in this, Please go through the whole help document as suggested in the classroom
