### ISSUE TITLE
Not able to Login Powershell azure

### ISSUE THREAD

**Issue by PavanRajuAlluri** [QT-DevOps/AzureIssues#51]
Even though i have fallowed steps proper way, I could not able to login powershell azure. I have below errors. Please help me on this.
![image](https://user-images.githubusercontent.com/61484277/75460018-d4d68e80-5978-11ea-8886-74bc385d31e6.png)

**Comment by srmanikanta** [comment]
Install azure Powershell:
--------------------------
It requires the below 
`$PSVersionTable`
*  powershell 5.1 or later
 * .Net framework 4.7.2 or later
Execute the commands:
`Install-Module -Name Az -AllowClobber -Scope AllUsers`
`Get-ExecutionPolicy`
`Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine`
`Connect-AzAccount`
Give crendential of azure account
