### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by GaneshAmalakanti** [QT-DevOps/AzureIssues#52]
while creating a subnet at the time of creation of network.im getting this warning
![IMG_20200304_194344602 1](https://user-images.githubusercontent.com/61587869/75888217-0c4dab00-5e51-11ea-9241-29b6510bf92a.jpg)

**Comment by GaneshAmalakanti** [comment]
imgetting a warning while adding subnet
![IMG_20200304_200124598 1](https://user-images.githubusercontent.com/61587869/75889684-4e77ec00-5e53-11ea-8326-dedf24db4abf.jpg)

**Comment by shaikkhajaibrahim** [comment]
That'ok those will be few changes for future
