### ISSUE TITLE
default subnet has been deleted by me & unable to get the Public IP address of EC2

### ISSUE THREAD

**Issue by sravya1610** [QT-DevOps/AzureIssues#53]
![image](https://user-images.githubusercontent.com/57889675/76277747-9792ca80-62af-11ea-8986-fcb96cd2aa74.png)

Also unable to get the Public IP address for created EC2 instance
![image](https://user-images.githubusercontent.com/57889675/76277895-1ee03e00-62b0-11ea-97b5-6a620a9a29ab.png)

Also getting connection timeout error when i gitbash

**Comment by srmanikanta** [comment]
whenever you launch an instance that time you have to enable `auto-assign public ip`
then only you get the public ip for ec2 machine.

**Comment by shaikkhajaibrahim** [comment]
Please raise AWS Issue in AWS Issues not here
