### ISSUE TITLE
Difference between a normal user and an AD user

### ISSUE THREAD

**Issue by Srilekha-31** [QT-DevOps/AzureIssues#54]
Sir, In today's class you were saying that there are two types of users , one is normal user and the other is AD user. for normal user RBAC is given at subscription/RG/resource level where as for a AD user role is assigned at Tenant level. Could you please elaborate on this i.e., how do we create a normal user. Creating AD user is Home |Default Directory |Users | All users > click on new user. 
but how do we create a normal user.

**Comment by srmanikanta** [comment]
The difference is the source of their authentication.

AD users are authenticated by a domain controller
Local users are authenticated locally.

**Comment by Srilekha-31** [comment]
I didn't get you..Could you please elaborate what you meant by local authentication.

**Comment by shaikkhajaibrahim** [comment]
AD user => authenticated by Active Directory which has been imported
normal user => created in azure
