### ISSUE TITLE
Can't connect to Linux VM

### ISSUE THREAD

**Issue by Srilekha-31** [QT-DevOps/AzureIssues#55]
I have created a linux vm and when i try to connect it is giving me the below error ,
 **LINUX VM :**
![image](https://user-images.githubusercontent.com/62125707/77029615-2dbaa500-69c2-11ea-801b-facfc41172b8.png)

**ERROR MSG:**
![image](https://user-images.githubusercontent.com/62125707/77029668-58a4f900-69c2-11ea-80d4-afaad55faee2.png)

**Comment by srmanikanta** [comment]
These are the reasons to fail
* check your vm is running
* open a port for rdp which is 3389
* use the public ip if you use `mstsc -v <publicip>` or download rdp file and double click on it.
please verify the things above

**Comment by shaikkhajaibrahim** [comment]
If it is linux machine why rdp, you should be using SSH
