### ISSUE TITLE
how to save run list in chef manage server

### ISSUE THREAD

**Issue by ram-1912** [QT-DevOps/AzureIssues#60]
there is no option to save t
<img width="960" alt="Annotation 2020-04-14 071528" src="https://user-images.githubusercontent.com/62230764/79177553-b93c2000-7e20-11ea-8f59-afae984c7e06.png">
he run list in edit node run list page

**Comment by NareshAbbanapuri** [comment]
hi
scroll down the page and click on save

**Comment by srmanikanta** [comment]
once you select the run_list of your node scroll down then you have find an option `save runlist`
then click on that
