### ISSUE TITLE
unable to open the cloud shell and getting this error

### ISSUE THREAD

**Issue by shravanpragallapati** [QT-DevOps/AzureIssues#62]
![image](https://user-images.githubusercontent.com/62504099/79290624-439c8680-7eea-11ea-9b67-c130719d1979.png)

**Comment by srmanikanta** [comment]
click on advenced settings and specify the details(don't forget to specify)
and finally create the account

**Comment by NareshAbbanapuri** [comment]
![advanced](https://user-images.githubusercontent.com/63383910/79560824-eeb56780-80c5-11ea-839c-219bd4965b89.jpeg)
change values in advanced settings

**Comment by shravanpragallapati** [comment]
I deleted that cloudshell rg and opened a new one that worked
