### ISSUE TITLE
upload the cookbook

### ISSUE THREAD

**Issue by ram-1912** [QT-DevOps/AzureIssues#63]
which commands are used to upload the cookbook to chef server  and how to chek if the cookbook is uploaded or not..

**Comment by srmanikanta** [comment]
ram this is azure issues repository if you have any issues related to devops raise an issue in devops issues repository.
solution  for your chef related question is:
* goto your cookbook  folder and then check berks file is present or not
* then execute the below commands
`berks install`
`berks upload `
* goto mange.chef.io then select nodes options at the top
--> click on run_list -->edit run_list-->drag your cookbook--> save run_list.
* goto your node exexute the below command
`sudo chef-client`

**Comment by ram-1912** [comment]
tq bro

**Comment by shaikkhajaibrahim** [comment]
Please raise devops issues in Devops Url
