### ISSUE TITLE
Regarding installing Azure CLI in Visual Studio

### ISSUE THREAD

**Issue by MadalaSwetha** [QT-DevOps/AzureIssues#64]
When I tried to install Azure Cli Tools in Visual Studio it shows "Failed to install 'ms-vscode.azurecli".  I am getting error while attaching file but issue is "Failed to install 'ms-vscode.azurecli".

**Comment by srmanikanta** [comment]
reinstall the azure cli tools extension

**Comment by MadalaSwetha** [comment]
Reinstalled after many trials it became success. Thank You for your support.
