### ISSUE TITLE
Regarding to create VM in azure CLI

### ISSUE THREAD

**Issue by MadalaSwetha** [QT-DevOps/AzureIssues#65]
When I try to create VM in Azure CLI getting error on sizes. Please find the attachment and help me to fix it.

![image](https://user-images.githubusercontent.com/39823207/79446543-fad4f280-7ffb-11ea-97e5-0611ee4b61e2.png)

**Comment by NareshAbbanapuri** [comment]
hi
please change your location

**Comment by MadalaSwetha** [comment]
I changed many location it shows this zone is not available for this
subscription or sizes are available in this zone. Either change location
nor change size. Please check once.

Regards,
Swetha .

**Comment by shaikkhajaibrahim** [comment]
Can you upload the new error

**Comment by vanurama2** [comment]
Hi,
     Please try to location 'Eastus'

**Comment by MadalaSwetha** [comment]
K

On 19 Apr 2020 9:06 pm, "vanurama2" <notifications@github.com> wrote:

Hi,
Please try to location 'Eastus'

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/QT-DevOps/AzureIssues/issues/65#issuecomment-616164268>,
or unsubscribe

**Comment by MadalaSwetha** [comment]
Please check I tried with eastus. Attached bellow screenshot.

**Comment by shaikkhajaibrahim** [comment]
No image over here @MadalaSwetha what ever you are trying to do in CLI, can you try in UI and share the screenshots

**Comment by vanurama2** [comment]
Hi MS,
        What u used commands in powershell, those are related to azure cli, not powershell. pls use the following commands in powershell and find the screen shot.
![image](https://user-images.githubusercontent.com/63392772/79944614-9c8b9200-8489-11ea-822a-6adf0a97759c.png)

**Comment by MadalaSwetha** [comment]
Hi VR,

Please find attached screenshot and I tried with your suggestion. It fails
again. I used commands are
New-AzResourceGroup -Name MSGroup1
New-AzVM -ResourceGroupName MSGroup1 -Name MSvm -Location 'Eastus' -Image
'win2016Datacenter'-Size 'Standard_B1s
I am unable to fix the issue with eatsus and westus as well
![VMError](https://user-images.githubusercontent.com/39823207/79950994-8be11900-8495-11ea-8dd3-bc7513129166.PNG)
. Could you please check this issue.

**Comment by vanurama2** [comment]
Hi,
    I think problem with subscription? send mail to microsoft.

**Comment by MadalaSwetha** [comment]
My Subscription is free trial and it is in enabled. I will send a email to Microsoft  for confirmation. Thank you
![SubAccountDetail](https://user-images.githubusercontent.com/39823207/80062294-01f68600-8551-11ea-93e1-0cb58b225cbe.PNG)

**Comment by MadalaSwetha** [comment]
I successfully fixed this issue. Thank you for your help.
