### ISSUE TITLE
azure cli

### ISSUE THREAD

**Issue by lokesh8433** [QT-DevOps/AzureIssues#68]
i get error in az cli

**Comment by lokesh8433** [comment]
![p1](https://user-images.githubusercontent.com/55614674/79625990-61682680-814a-11ea-9fae-86741dc47973.png)

**Comment by shaikkhajaibrahim** [comment]
Can you run the command in administrator mode and  send me the output of
python --version command

**Comment by lokesh8433** [comment]
i am run in administrator 
![p2](https://user-images.githubusercontent.com/55614674/79678513-03a30f80-821a-11ea-8151-0c120007c7ec.png)
![p2](https://user-images.githubusercontent.com/55614674/79678518-0d2c7780-821a-11ea-80bd-3b45b15b147b.png)

**Comment by lokesh8433** [comment]
i given az --version and python --version both of them get same error

**Comment by shravanpragallapati** [comment]
Even I got the same error
Try these steps:
Install-Module -Name Az -AllowClobber -Scope AllUsers
Get-ExecutionPolicy
Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine
Connect-AzAccount

Regards, 
Shravan 9491185145 :)

**Comment by srmanikanta** [comment]
check the az cli and python is installed or not 
if not install az cli and python and check the versions.

**Comment by NareshAbbanapuri** [comment]
Hi
please uninstall python 
and install python (choco install python3)

**Comment by lokesh8433** [comment]
Hi
![p3](https://user-images.githubusercontent.com/55614674/79841575-3f360900-83d5-11ea-9b4e-a2e1fba1167a.png)

i do uninstall python and reinstall python 
i given python --version and az --version but i get same error

**Comment by shaikkhajaibrahim** [comment]
Strange error lokesh
python is not working on your laptop
& if python doesnot work azure cli will not
I would recommend using cloud shell

By the way findout why python is failing look into event viewer
We cant help if python is crashing
