### ISSUE TITLE
Unable to connect to jenkins after installing jenkins in ubuntu/xenial64. Jenkins service is running, still unable to connect.

### ISSUE THREAD

**Issue by suryaDevops1** [QT-DevOps/AzureIssues#7]
![jenkins](https://user-images.githubusercontent.com/50073841/57008883-d62c1300-6c10-11e9-8aaf-61187453a8d7.png)

**Comment by Karthick-Gopalakrishnan** [comment]
hello Surya,

Kindly move it to DEVOPS issue

**Comment by anon-42** [comment]
did you created ingress rule for port 8080 ?

**Comment by nareshabbanapuri** [comment]
please enable public ip by default its disable
