### ISSUE TITLE
cannot connect to VM using RDP or SSH from mac

### ISSUE THREAD

**Issue by azuraspirant** [QT-DevOps/AzureIssues#70]
I have create new azure VM. then i have SSH and RDP options to connect, i used RDP connector but it says, cannot connect. any options cloud or physical to connect to VM from MAC? thank you in advance.

**Comment by NareshAbbanapuri** [comment]
Hi 
please share logs 
open 3389 port

**Comment by shaikkhajaibrahim** [comment]
First the VM Which you have created is windows or linux
and please share screenshots of azure and mac terminal error which you are recieving

**Comment by azuraspirant** [comment]
i can connect to vm via cloud shell. i followed below article. but i cannot login to my vm via rdp in windows RDP and Mac RDP. please help. 

https://docs.microsoft.com/en-us/azure/cloud-shell/quickstart


<img width="556" alt="Screen Shot 2020-04-22 at 10 26 59 PM" src="https://user-images.githubusercontent.com/63988141/80052842-a3e28800-84e9-11ea-8658-d7efe9bd5b94.png">
![RDP-connection-failed](https://user-images.githubusercontent.com/63988141/80052844-a3e28800-84e9-11ea-8b1e-8959cd0f7b2a.png)

**Comment by azuraspirant** [comment]
![RDP-connection-failed](https://user-images.githubusercontent.com/63988141/80052931-caa0be80-84e9-11ea-8a43-24f7f683518d.png)

**Comment by srmanikanta** [comment]
please check the port number 3389 is opened in your network security or not.
