### ISSUE TITLE
Unable to open the public ip in the browser

### ISSUE THREAD

**Issue by vanurama2** [QT-DevOps/AzureIssues#73]
Hi ,
Create a Virtual Machine
Connected the VM using github and executed the below commands

sudo apt update
sudo apt install stress –y
sudo apt install apache2 –y
sudo apt install php libapache2-mod-php php-mysql –y
sudo systemctl enable apache2
sudo systemctl restart apache2
sudo nano /var/www/html/info.php
<?php
phpinfo();
?>

sudo systemctl restart apache2

Below URL entered in the browser
http://13.68.152.195/info.php
The Error message "This site can’t be reached" was displayed

**Comment by srmanikanta** [comment]
check 80 port is opened or not in network security group
and try http://<publicip>:80
it displays default home page for webserver once the homepage  is displayed
then try http:<publicip>:80/info.php
Note: execute this command  `ping <publicip>` this for checking the network connection. and above is verified then update the isuue.

**Comment by vanurama2** [comment]
Can u share screen shot or provide steps, where can find the network
security tab to check port 80 is enabled or not

**Comment by srmanikanta** [comment]
please follow issue no:71

**Comment by vanurama2** [comment]
Now, Working fine.
