### ISSUE TITLE
i created a "VM IMAGE,LOADBALANCER and VMSS" then i tried to login using my loadbalancer ip address but im not able to login

### ISSUE THREAD

**Issue by GaneshAmalakanti** [QT-DevOps/AzureIssues#75]
ssh -p 50000 qtdevops@52.154.154.246

ssh: connect to host 52.154.154.246 port 50000: Connection timed out

**Comment by srmanikanta** [comment]
Procedure to change the SSH Port for Linux or Unix Server
Open the terminal application and connect to your server via SSH.
Locate sshd_config file by typing the find command.
Edit the sshd server file and set Port option.
Save and close the file.
Restart the sshd service to change the ssh port in Linux.

Are you did this?
if not no need to mention `-p ` option in ssh, it is used default port(22)
commad is `ssh username@ip`

**Comment by GaneshAmalakanti** [comment]
i tried it ssh username@ip
same result

**Comment by srmanikanta** [comment]
create one vm and then install lamp stack. 
then create an image,follow this [link](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource)
read these documents one by one and try
[click here-1](https://directdevops.blog/2020/04/20/azure-classroom-series-20-apr-2020/)
[click here-2](https://directdevops.blog/2020/04/21/azure-classroom-series-21-apr-2020/)
[click here-3](https://directdevops.blog/2020/04/22/azure-classroom-series-22-apr-2020/)
please find the steps where you are missed out.
if you are not resolved the issue then update the issue.

**Comment by GaneshAmalakanti** [comment]
i installed lampstack and created image sucessfully then i created a loadbalancer and vmss  
  but still iam getting 'Connection timed out'

**Comment by srmanikanta** [comment]
hi ganesh,
I think your are not done this job correctly please read the above documents one by  one and then try.
if you already resolve the issue please close the issue.
