### ISSUE TITLE
Azure DevOps

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/AzureIssues#77]
Hi Friends
Can some one please let me know any difference between DevOps and Azure DevOps.. ?

**Comment by srmanikanta** [comment]
devops and Azure devops both are conceptually same let us discuss what we do in devops and what we do in azure devops.
In devops :
you have to create the server and install the required soft wares.
you have to maintain the backups and high availability etc..
for example:
if you want a jenkins server, first in first you take one server and install jenkins on that server.
backup and high availability etc.,  you are responsible person.
In simple terms you are the responsible for everything in devops

In azure devops:
azure cloud provider provide the devops tools as a service(software as a service)
they are responsible for maintain high availability and backups etc..
for example:
if you want jenkins just goto azure devops they are provide jenkins as a service just use it.
they are the responsible for backup, and highavailability etc..
In simple terms they are responsible for everything just you have to use those services. 

My assumption is azure devops make your life simple. but before going to azure devops you should know all the manual things in devops.

I think this is useful to you if not please ignore.

**Comment by SajidAliKhanMohammed** [comment]
Thanks Manikanta for your valuable clarification..
