### ISSUE TITLE
maven

### ISSUE THREAD

**Issue by prasannalaxmi1013** [QT-DevOps/AzureIssues#81]
sudo apt-get  update  run this command,,next view is (sudo)  password for jenkins  ....any password is given not accept sir...

**Comment by srmanikanta** [comment]
hi prasannalaxmi, follow these steps
1. set password for jenkins user, command is `passwd jenkins`
2. next add the jenkins user in /etc/sodeors file, command is `visudo` . once opened that file then find this line `%sudo   ALL=(ALL:ALL) ALL` add this line in the below  `jenkins   ALL=(ALL:ALL) NOPASSWD:ALL`  
3. save the file.

if you resolve the issue. please close the issue.

**Comment by srmanikanta** [comment]
hi prasannalaxmi, please close the issue.
