### ISSUE TITLE
Groovy error

### ISSUE THREAD

**Issue by mruttala** [QT-DevOps/AzureIssues#82]
hello,
i installed groovy on my system and when i wrote the script and tried to run, im getting an error stating: java.lang.NoClassDefFoundError: Unable to load class org.apache.groovy.jaxb.extensions.JaxbExtensions due to missing dependency javax/xml/bind/JAXBContext

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

where i went wrong???

**Comment by srmanikanta** [comment]
hi mruttala, please refer [here](https://stackoverflow.com/questions/51625143/cant-launch-groovy-console-missing-dependency-javax-xml-bind-unmarshaller)

**Comment by mruttala** [comment]
NO, i it didn't resolved. actually in system environment variables, i gave GROOVY_HOME  name and  path as C:\tools\groovy-3.0.3\bin and when i tried to execute in power shell and im getting an error:
'findstr' is not recognized as an internal or external command,
operable program or batch file.
Error: Could not find or load main class org.codehaus.groovy.tools.GroovyStarter
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.tools.GroovyStarter

**Comment by srmanikanta** [comment]
hi mruttala, please set the path correctly or uninstall the grovy and reinstall again.

**Comment by mruttala** [comment]
I uninstalled and installed groovy installer , but still im getting an error as : "findstr is not recognised as internal or external command . "

**Comment by srmanikanta** [comment]
please call this number 7893532934.

**Comment by NareshAbbanapuri** [comment]
hi 
use chocolatey
choco install groovy --force

**Comment by mruttala2122** [comment]
done but still im getting the erroer while running the script."
"findstr' is not recognized as an internal or external command,
operable program or batch file." 
this is the error

**Comment by mruttala** [comment]
done but still im getting the erroer while running the script."
"findstr' is not recognized as an internal or external command,
operable program or batch file."
this is the error
