### ISSUE TITLE
AWS S3 BUCKET

### ISSUE THREAD

**Issue by mruttala** [QT-DevOps/AzureIssues#85]
while creating s3 bucket, im getting the foll. error 
I gave  in the script , the provider :aws , s3 bucket name : myawss3bucket
its stating that bucket name is already available and i tried with numerous times with so many other names but i still im getting same error.
C:\Devops\Terraform\s3inaws>  terraform apply "s3inaws.plan"
aws_s3_bucket.myawss3bucket: Creating...

Error: Error creating S3 bucket: BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.
        status code: 409, request id: A8021566F5265E12, host id: iht5XrLAg2t0U1CObLBaO6oIB6jXgOBWsPPQQeaojHEl2qNCac39V96hqW9KWkqy8BwfRAkfOrc=

  on main.tf line 7, in resource "aws_s3_bucket" "myawss3bucket":
   7: resource "aws_s3_bucket" "myawss3bucket" {

**Comment by srmanikanta** [comment]
hi mruttala,
S3 is a universal namespace, i.e., the names must be unique globally. Bucket contains a DNS address. Therefore, the bucket must contain a unique name to generate a unique DNS address.
