### ISSUE TITLE
Not getting key pairs in aws

### ISSUE THREAD

**Issue by Phani-Thulabhandula** [QT-DevOps/AzureIssues#86]
![Screenshot (42)](https://user-images.githubusercontent.com/66129605/83342037-44318680-a2b8-11ea-96a3-a49f240c00b0.png)

unable to get key pairs. How to access them?

**Comment by ramjagadeeshkumar** [comment]
When your launch EC2 instance will ask to create keypair or use existing keypair

If you create existing keypair if keypair is not available 
Then there is no way to login directly

With out keypair can login via system manager service in Aws

**Comment by Phani-Thulabhandula** [comment]
ok tq
