### ISSUE TITLE
Error: No configuration files

### ISSUE THREAD

**Issue by Phani-Thulabhandula** [QT-DevOps/AzureIssues#87]

**Comment by neelaraokala** [comment]
that means your have to run the command terraform init on your exact directory where your .tf file is consists. 
1. make sure your file name has .tf extention.  ex: <foldername>.tf
2. change to the directory  consists of configuration file(.tf file) .
3. then run "terraform init"

**Comment by srmanikanta** [comment]
hi phani,
first create a directory and then create terraform files actually the extension is .tf so please ensure your directory contains .tf fiels or not
once you created the terraform files then initialize the directory by using this command `terraform init`
once you initialization is happen  then validate your terraform filesby using `terraform validate .` , the validation is success then apply the configuration by using `terraform apply .` command.

Note: This is an azure repository please raise an issue in devops repository from next onwords.

**Comment by Phani-Thulabhandula** [comment]
ok tq its resolved.

**Comment by ramjagadeeshkumar** [comment]
Close the issue
