### ISSUE TITLE
Unable to configure AzureMigration Appliance VM

### ISSUE THREAD

**Issue by ramoct15** [QT-DevOps/AzureIssues#88]
On trying to "Import Virtual Machine"using Hper V VM getting below error.
![image (1)](https://user-images.githubusercontent.com/62635821/83402320-28e38a00-a424-11ea-907e-b4222f32f34c.png)

Sir, Kindly check and do needful

**Comment by ramjagadeeshkumar** [comment]
Give the process 4 and ram 8gb is required
