### ISSUE TITLE
Error while trying to create s3 bucket

### ISSUE THREAD

**Issue by Phani-Thulabhandula** [QT-DevOps/AzureIssues#89]
![Screenshot (17)](https://user-images.githubusercontent.com/66129605/83718460-12dff000-a603-11ea-8243-bea4266c9074.png)
![Screenshot (15)](https://user-images.githubusercontent.com/66129605/83718461-13788680-a603-11ea-85bf-f59b182109a7.png)
![Screenshot (16)](https://user-images.githubusercontent.com/66129605/83718463-14111d00-a603-11ea-87f5-3a4698383e89.png)

**Comment by ramjagadeeshkumar** [comment]
Please check IAM user permissions

**Comment by srmanikanta** [comment]
please provide the access key and secret key and region name in provider or just set an environment variable.
example  for provider
```
provider "aws" {
  region     = "us-west-2"
  access_key = "my-access-key"
  secret_key = "my-secret-key"
}
```
example for environment variables
```
export AWS_ACCESS_KEY_ID="anaccesskey"
export AWS_SECRET_ACCESS_KEY="asecretkey"
export AWS_DEFAULT_REGION="us-west-2"
``` 
note: provide your access key, secret key and region.

**Comment by Phani-Thulabhandula** [comment]
Im trying to give environment variables. In class we are taught to give them like this in run  time.
$env:AWS_ACCESS_KEY_ID="."
like wise the other two.
and in provider.tf provider "aws" {
}

and we are following this method.

**Comment by srmanikanta** [comment]
please check your environment variables once. are you set environment variables permanently or not?
please check,the error  is related to your aws credentials.
