### ISSUE TITLE
OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054 error while downloading os through vagrant 

### ISSUE THREAD

**Issue by krishnapusuluri** [QT-DevOps/AzureIssues#9]
Hi All,

some times when we will get "OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054" while issuing command "vagrant box add bento/ubuntu-16.04" for hypder-v so please use as below to over come it
vagrant box add bento/ubuntu-16.04 http://vagrantcloud.com/bento/ubuntu-16.04

(vagrant box add <provider/os-version> http://vagrantcloud.com/provider/os-version)

Hope it will help you

**Comment by ghost** [comment]
ok Krishna , i think you give suggestion to who  have  facing this problem. thanks
please close issue
