### ISSUE TITLE
Regarding while building (docker image build -t hellodocker .) an image file

### ISSUE THREAD

**Issue by MadalaSwetha** [QT-DevOps/AzureIssues#90]
Getting error like file not found while building an image.
Details: 
Dir name: hellodocker
File name: dockerimage
Pwd: /root
used command: docker image build -t hellodocker .

Please find attachments below and help to fix the issue.

![image](https://user-images.githubusercontent.com/39823207/84354984-78be1000-abdf-11ea-9f70-5383db8ff3dc.png)

![image](https://user-images.githubusercontent.com/39823207/84355113-af942600-abdf-11ea-9cd4-e0d74fb9be3d.png)

**Comment by neelaraokala** [comment]
Hi MadalaSwetha,
there is nothing wrong, what you did was absolutely correct. i think your using Docker playground, if it is yes,
kindly delete the current running instance, and lunch new instance , it will work. these are problems with Docker playground behavior .
one more suggestion :
to run spring-pet-clinic , you need base image with capable of Java support . so you can directly select a image which supports java ex: openjdk:8
so , dockerfile will be like **
FROM openjdk:8
RUN wget https://referenceappkhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar
EXPOSE 8080
CMD ["java",  "-jar",  "spring-petclinic-2.2.0.BUILD-SNAPSHOT.jar"]**

**Comment by MadalaSwetha** [comment]
Okay. I will try it. Thank you.
