### ISSUE TITLE
K8's : Observing connectivity issue between Working Node and Master Node - Post running Kubeadm init

### ISSUE THREAD

**Issue by ramoct15** [QT-DevOps/AzureIssues#92]
Unable to map Working node to Master Node in the kubectl cluster

Steps : (Master & Working Node)
sudo apt-get update
sudo apt-get install docker.io
sudo apt-get update && sudo apt-get install -y apt-transport-https
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
sudo apt-get update
sudo apt-get install -y kubelet kubeadm kubectl
sudo apt-mark hold kubelet kubeadm kubectl

Master Node (Root User) : Kubeadm init

Master Node (Normal User) : 
  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config

MasterNode (Normal User) : Pod Network connectivity
kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

Working Node (Root User) : Executed below command

kubeadm join 10.0.0.7:6443 --token 4l2gx7.q82xnl79v339hyyf \
    --discovery-token-ca-cert-hash sha256:e2b4454d23feec2a8184fd1c3c6c1b71ff3c3e8c39f2963a20a983f5feb16b7d

Note : Tried reset kubeadm reset -f (Master Node) and performed kubeadm init ---> but below issue still exists
**Issue :** 
root@node:~# kubeadm join 10.0.0.7:6443 --token 4l2gx7.q82xnl79v339hyyf \
>     --discovery-token-ca-cert-hash sha256:e2b4454d23feec2a8184fd1c3c6c1b71ff3c3e8c39f2963a20a983f5feb16b7d
W0711 19:03:46.103485   19848 join.go:346] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
[preflight] Running pre-flight checks
**error execution phase preflight: couldn't validate the identity of the API Server: Get https://10.0.0.7:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
To see the stack trace of this error execute with --v=5 or higher**

Kindly check and update.

**Comment by srmanikanta** [comment]
open port 6443 in network security rules

**Comment by ramoct15** [comment]
Got the issue resolved already.

Thank you
