### ISSUE TITLE
Jenkins container 2 ports

### ISSUE THREAD

**Issue by kvbr999** [QT-DevOps/AzureIssues#94]
when docker container for jenkins is created, there are two ports, I can see. why two ports for application. Is that some applications need more than one port?
![twoPorts](https://user-images.githubusercontent.com/64296747/91168266-fa0f4400-e6f2-11ea-92d4-2bb97743c0f6.png)

**Comment by ramjagadeeshkumar** [comment]
jenkins image listens on 8080, and I'd like to run more than one service whose image listens on 8080, so I'd like to do:

ports:
  - 8081:8080
but any remapping of the ports at the service level 

Do n't need multiple port  for any application
