### ISSUE TITLE
Unable to create the instance on AWS using Kitchen

### ISSUE THREAD

**Issue by venky9063** [QT-DevOps/AzureIssues#96]
Hi Team,

I am unable to create the VM on AWS using the Kitchen Create. I have updated the AWS credentials like access_key_id and secret_key in Chef-repo/.chef/config.rb. Even though i am facing the issue.

Please advise. 

Regards,
Venkatesh.

ubuntu@ip:~/chef-repo/cookbooks/mongo$ kitchen create
-----> Starting Test Kitchen (v2.5.2)
-----> Creating <default-ubuntu-1804>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [unable to sign request without credentials set] on default-ubuntu-1804
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by srmanikanta** [comment]
please check the aws cli is configured in which region you are take ami, security group and pemfile and all.
if not configure correctly and then try

**Comment by shaikkhajaibrahim** [comment]
Please Raise AWS Issues in AWS Forum not here
