### ISSUE TITLE
Issue while doing test kitchen setup with AWS.

### ISSUE THREAD

**Issue by SBqt** [QT-DevOps/AzureIssues#97]
I created a cookbook using chef generate cookbook -b kitchenawsdemo. I got the following errors but eventually cookbook was created in the folder but then i used to type aws configure, the first step towards setting test kitchen, ita not working. 
Please help me how to overcome this issue.
![Capture1](https://user-images.githubusercontent.com/71276753/93106004-5e5b6d00-f6cd-11ea-806d-41a524ff508b.JPG)
![Capture2](https://user-images.githubusercontent.com/71276753/93106009-60bdc700-f6cd-11ea-85c3-2ce67f556bb3.JPG)
![Capture3](https://user-images.githubusercontent.com/71276753/93106015-61565d80-f6cd-11ea-8ea4-a866bffb5d36.JPG)
![Capture4](https://user-images.githubusercontent.com/71276753/93106020-62878a80-f6cd-11ea-973c-d96c94ac0945.JPG)

**Comment by srmanikanta** [comment]
I already answer this question in issue number `98` so follow the steps and close the issue.
